name: Check
on: [pull_request]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v6
      - uses: cachix/cachix-action@v3
        with:
          name: knopki-nixexprs
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          skipNixBuild: true
      - run: nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
      - run: nix-channel --update
      - run: nix-shell --run "pre-commit run -a"

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          - "https://nixos.org/channels/nixos-19.09"
          - "https://nixos.org/channels/nixos-unstable"
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v6
      - run: nix-channel --add ${{ matrix.channel }} nixpkgs
      - run: nix-channel --update
      - run: nix eval -f default.nix 'lib'
      - run: nix eval -f default.nix 'modules'
      - run: nix eval -f default.nix 'overlays'
      - uses: cachix/cachix-action@v3
        with:
          name: knopki-nixexprs
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          file: ci.nix
          attributes: cacheOutputs
      - run: nix-build ci.nix -A buildOutputs
